spring:
  application:
    name: spring-ai
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-917a68f01914486cb504154baaf73f23
      chat:
        options:
          model: deepseek-v3.1
