spring:
  application:
    name: spring-ai
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-917a68f01914486cb504154baaf73f23
      chat:
        options:
          model: deepseek-v3.1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.94:3306/ls_test?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
    username: lsTest
    password: aP4d9K

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
    com.learn.springai: DEBUG
